# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies => Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Datatbase for Write From Dictation Skill
wfd = { "Mar19_1.mp3" => "Archaeologists discovered tools and artifacts in ancient tombs.",
        "Mar19_2.mp3" => "Blue whale is the largest mammal that ever lived.",
        "Mar19_3.mp3" => "Children conquer their first language without any efforts.",
        "Mar19_4.mp3" => "Essay and assignment are spread across the academic year.",
        "Mar19_5.mp3" => "Even simple techniques need to be practiced to become perfect.",
        "Mar19_6.mp3" => "Firm conclusions can be established through rigorous experiments.",
        "Mar19_7.mp3" => "Graphs are often useful for geographical research.",
        "Mar19_8.mp3" => "Horizontal line on the graph indicates there is no change.",
        "Mar19_9.mp3" => "International exchanges formulate the study of our program.",
        "Mar19_10.mp3" => "It is successfully acknowledged that there is a student graduation ceremony.",
        "Mar19_11.mp3" => "It takes a long time to walk to university.",
        "Mar19_12.mp3" => "Late applications are not accepted under any circumstances.",
        "Mar19_13.mp3" => "Make sure you have saved all the files before turning off the computer.",
        "Mar19_14.mp3" => "Measures must be taken to prevent the unemployment rate from rising.",
        "Mar19_15.mp3" => "Momentum is defined as a combination of mass and velocity.",
        "Mar19_16.mp3" => "Salt is extracted from seawater from the ground.",
        "Mar19_17.mp3" => "Slides and handouts can be downloaded after the lecture.",
        "Mar19_18.mp3" => "Social media is a criticism of critical decisions.",
        "Mar19_19.mp3" => "Sociology policies are the sources of government to solve social problems.",
        "Mar19_20.mp3" => "Sound waves are unable to travel through the vacuum.",
        "Mar19_21.mp3" => "Statistically speaking, the likelihood of the result is extremely low.",
        "Mar19_22.mp3" => "Students should leave their bags on the table by the door.",
        "Mar19_23.mp3" => "The area has a number of underwater habitats in species.",
        "Mar19_24.mp3" => "The coffee machine on the third floor is not working today.",
        "Mar19_25.mp3" => "The collapse of the housing market makes recessions.",
        "Mar19_26.mp3" => "The course tomorrow will require higher skill levels.",
        "Mar19_27.mp3" => "The north campus car park could be closed on Sunday.",
        "Mar19_28.mp3" => "The reception staff can give information about renting and printing.",
        "Mar19_29.mp3" => "The reception staff give advices about renting accommodation.",
        "Mar19_30.mp3" => "There is a widely believed perception that engineering is for boys.",
        "Mar19_31.mp3" => "You must set a security question when resetting your password.",
        "Mar19_32.mp3" => "Your ideas are discussed depending on your seminar or tutorial.",
        "Feb19_1.mp3" => "A balanced diet and regular exercise are necessary for good health.",
        "Feb19_2.mp3" => "A good way to improve vocabulary is repetition.",
        "Feb19_3.mp3" => "A lack of sleep can increase the chance of some illnesses.",
        "Feb19_4.mp3" => "A number of assignments will be gathered to the conference.",
        "Feb19_5.mp3" => "A rising population means more trees are cut down.",
        "Feb19_6.mp3" => "An undergraduate is required to do many projects.",
        "Feb19_7.mp3" => "Art students often exhibit their works on the university buildings.",
        "Feb19_8.mp3" => "Both staff and students can purchase car parking permits online.",
        "Feb19_9.mp3" => "Check the website if you are looking for discounted textbooks.",
        "Feb19_10.mp3" => "Consumer confidence tends to increase as the economy expands.",
        "Feb19_11.mp3" => "Continuing students will be sent for application forms.",
        "Feb19_12.mp3" => "Distance learning can develop your career around the world.",
        "Feb19_13.mp3" => "Farming methods across the world have greatly developed recently.",
        "Feb19_14.mp3" => "Global connections increased in academic communities, thanks to social media.",
        "Feb19_15.mp3" => "Growing population has posed a challenge to many governments.",
        "Feb19_16.mp3" => "In this book, the author discussed the role of cultural differences.",
        "Feb19_17.mp3" => "Industrial experts will discuss job opportunities in an automatic labor force.",
        "Feb19_18.mp3" => "It was four more years before the theory was fully developed.",
        "Feb19_19.mp3" => "It would be extremely beneficial to work together.",
        "Feb19_20.mp3" => "Key business partners are often entertained in expensive accounts.",
        "Feb19_21.mp3" => "Ladies have the popular forms of entertainments throughout the world.",
        "Feb19_22.mp3" => "Library plays an important role in student's life.",
        "Feb19_23.mp3" => "Managing the increasing population is the challenge for most governments.",
        "Feb19_24.mp3" => "Manufacturing now brings more people in than agriculture and fishing combined.",
        "Feb19_25.mp3" => "One of the functions of the internal organ is to keep the body warm.",
        "Feb19_26.mp3" => "Our courses help to improve critical thinking and independent learning skills.",
        "Feb19_27.mp3" => "Please ensure you do not go above word limitation.",
        "Feb19_28.mp3" => "Please provide the reports to support your idea of these arguments.",
        "Feb19_29.mp3" => "Please write the name of author and the year of publication.",
        "Feb19_30.mp3" => "Reading list will be available before the course begins.",
        "Feb19_31.mp3" => "Science library is currently located on the ground of the library.",
        "Feb19_32.mp3" => "Strangely, people are impacted by spontaneously using statistics.",
        "Feb19_33.mp3" => "Student advisor was aware that lecture today has been cancelled.",
        "Feb19_34.mp3" => "Students who study overseas can significantly improve work chances.",
        "Feb19_35.mp3" => "Take the first step to apply your university scholarship.",
        "Feb19_36.mp3" => "The course dates are available on the college website.",
        "Feb19_37.mp3" => "The invention of the printing press increases the demand for paper.",
        "Feb19_38.mp3" => "The new art gallery can only be visited on Fridays.",
        "Feb19_39.mp3" => "The office hours will be changed from next term.",
        "Feb19_40.mp3" => "The teacher training is an observation of the classes.",
        "Feb19_41.mp3" => "The temperature in summer is lower when comparing to the hall.",
        "Feb19_42.mp3" => "The university should introduce technology to support learning.",
        "Feb19_43.mp3" => "There are opportunities to receive the grants from most artistic fields.",
        "Feb19_44.mp3" => "There is a significant difference between theory and practice in education.",
        "Feb19_45.mp3" => "There will be a meeting for the first-year students on Friday.",
        "Feb19_46.mp3" => "These leaflets can be really useful when you are revising.",
        "Feb19_47.mp3" => "They develop a unique approach to train their employees.",
        "Feb19_48.mp3" => "Today's history lecture has been moved to lecture theater.",
        "Feb19_49.mp3" => "Universities invest new technology designed for learning.",
        "Feb19_50.mp3" => "Universities need to secure the grants for research subjects.",
        "Feb19_51.mp3" => "We are achieving common prosperity throughout the department.",
        "Feb19_52.mp3" => "Without doubt, this theory has a number of limitations.",
        "Feb19_53.mp3" => "You can ask your tutor for a further assistance.",
        "Feb19_54.mp3" => "You must figure out the mathematical problems and apply what you learned.",
        "Feb19_55.mp3" => "Much of the research is carried out in this laboratory.",
        "Jan19_1.mp3" => "Today we will look at how to play the data visually.",
        "Jan19_2.mp3" => "The studies showed the Hongkong people are most active in Asia.",
        "Jan19_3.mp3" => "Unemployment rate has fallen to its lowest level in years.",
        "Jan19_4.mp3" => "Please provide the reports to support your idea of these arguments.",
        "Jan19_5.mp3" => "Get enough sleep the night before the test.",
        "Jan19_7.mp3" => "Every student has a regular meeting with his or her personal tutor.",
        "Jan19_8.mp3" => "More research is needed before any definitive conclusion is drawn.",
        "Jan19_9.mp3" => "Rising in temperature is changing the wildlife population.",
        "Jan19_10.mp3" => "Doing nothing is not always better than taking risks.",
        "Jan19_11.mp3" => "All lectures and learning materials can be found on the internet.",
        "Jan19_12.mp3" => "The poster of this play is hung in the large lecture theater.",
        "Jan19_13.mp3" => "Students who attempt to go to the conference must register now.",
        "Jan19_14.mp3" => "Although sustainable development is not easy, it is our responsibility.",
        "Jan19_15.mp3" => "There have been many changes recently in the mathematics department.",
        "Jan19_16.mp3" => "This course puts great emphasis on critical thinking skills.",
        "Jan19_17.mp3" => "Our food supply now contains too much sugar that our metabolic system cannot handle it.",
        "Jan19_18.mp3" => "Several candidates will be qualified as the greatest scientists in all time.",
        "Jan19_19.mp3" => "The visiting speaker used to be a lecturer in this department.",
        "Jan19_20.mp3" => "Research shows the exercising makes us feel better.",
        "Jan19_21.mp3" => "There are not much interconnections between philosophy and psychology.",
        "Jan19_22.mp3" => "Unlike short sleep, overlong sleep increases the risk of illness.",
        "Jan19_23.mp3" => "The seminar provided an opportunity to exchange ideas with other students.",
        "Jan19_24.mp3" => "New credit cards will soon use the finger press technology.",
        "Jan19_25.mp3" => "Theater study courses encourage students to exercise creativity.",
        "Jan19_26.mp3" => "Your application for research grant has been received.",
        "Jan19_27.mp3" => "The Industrial Revolution in Europe was driven by steam technology.",
        "Jan19_28.mp3" => "Our laboratory equipment is provided free of charge.",
        "Jan19_29.mp3" => "There are many good reasons to grow trees in more cities.",
        "Jan19_30.mp3" => "Unusual weather patterns are making farming more difficult today.",
        "Jan19_31.mp3" => "The cooperator operates a continuous assessment.",
        "Jan19_32.mp3" => "The body fat keeps internal organs warm.",
        "Jan19_33.mp3" => "Mature students usually adapt to university life extremely well.",
        "Jan19_34.mp3" => "Governments need to make solar energy more affordable to everyone.",
        "Jan19_35.mp3" => "All the course stages are on the website.",
        "Jan19_36.mp3" => "Protective clothing must always be worn in the laboratory.",
        "Jan19_37.mp3" => "Peer review is a central part of scientific method.",
        "Jan19_38.mp3" => "Even if you have used cosmetics for years without problems, one or more ingredients can still trigger.",
        "Jan19_39.mp3" => "Economic development needs to be supported by the government.",
        "Jan19_40.mp3" => "A good research assistant is not afraid to ask questions.",
        "Jan19_41.mp3" => "An architect requires of problem-solving skills and an eye of design.",
        "Jan19_42.mp3" => "Calculations may not be needed in this examination.",
        "Jan19_43.mp3" => "He was constantly looking for ways to bring industry and agriculture closely together",
        "Jan19_44.mp3" => "In his lifetime, he composed most of the works.",
        "Jan19_45.mp3" => "Novelists write things about things they know about.",
        "Jan19_46.mp3" => "Students should take advantage of the online resources before attending the lecture.",
        "Jan19_47.mp3" => "Students who attempt to go to the conference must register now",
        "Jan19_48.mp3" => "The poster of this play is hung in the large lecture theatre.",
        "Jan19_49.mp3" => "The theater courses are encouraging students to access creativity.",
        "Jan19_50.mp3" => "There are many branches of medical studies.",
        "Jan19_51.mp3" => "There have been many changes/struggles in mathematics department.",
        "Jan19_52.mp3" => "This course considerably emphasizes on the critical thinking skills.",
        "Jan19_53.mp3" => "Tutors should set a clear goal at the start of the class.",
        "Jan19_54.mp3" => "There is a difference between mass production and batch production.",
        "2018collection_01.mp3" => "She used to be the editor of the student newspaper",
        "2018collection_02.mp3" => "The lecture tomorrow will discuss educational policies in the United States.",
        "2018collection_03.mp3" => "Mutually exclusive eventrhs can be described as either complementary or opposite.",
        "2018collection_04.mp3" => "The students were instructed to submit their assignments before Friday.",
        "2018collection_05.mp3" => "The placement test of mathematics and statistics is offered to every semester.",
        "2018collection_06.mp3" => "The article illyustrates a number of very interesting experiments.",
        "2018collection_07.mp3" => "It is hard to anticipate all the different characters that thhey react.",
        "2018collection_08.mp3" => "The business policy seminar includes an internship with a local firm.",
        "2018collection_09.mp3" => "Remember review all sources before drawing any conclusions.",
        "2018collection_10.mp3" => "University departments should carefully monitor articles and other publications by faculty.",
        "2018collection_11.mp3" => "Your lowest quiz grade has been omitted from the calculations.",
        "2018collection_12.mp3" => "We cannot consider an incremase in price at this stage.",
        "2018collection_13.mp3" => "The qualification will be assessed by using the criterion reference to approach.",
        "2018collection_14.mp3" => "Students were instructed to submit their assignments by Friday. ",
        "2018collection_15.mp3" => "The massive accumulation of data is converted into a communicable argument.",
        "2018collection_16.mp3" => "Student concession cards can be obtained by completing an application form.",
        "2018collection_17.mp3" => "A party was thrown in a small meeting room. ",
        "2018collection_18.mp3" => "An aerial photograph was promptly registered for a thorough evaluation. ",
        "2018collection_19.mp3" => "Behind the garage, there is a flat car drawn by mules.",
        "2018collection_20.mp3" => "I thought it was thrown in the small meeting room.",
        "2018collection_21.mp3" => "Everyone must evacuate the premises during the fire drill.",
        "2018collection_22.mp3" => "Free campus tours run daily during summer for prospective students.",
        "2018collection_23.mp3" => "The artist tied conservative politicians earned their roles of critics.",
        "2018collection_24.mp3" => "Radio is a popular form of entertainment throughout the world.",
        "2018collection_25.mp3" => "Remember to sign the attendance register before leaving the hall.",
        "2018collection_26.mp3" => "Observers waited nervously and with bated the breath for the concert.",
        "2018collection_27.mp3" => "Those students seeking for further extension should talk to their faculties for more information.",
        "2018collection_28.mp3" => "Most students have not considered these issues before.",
        "2018collection_29.mp3" => "Many graduates studying journalism get jobs in communications field.",
        "2018collection_30.mp3" => "Before submitting your dissertation, your advisor must approve your application.",
        "2018collection_31.mp3" => "Synopsis contains the most important information.",
        "2018collection_32.mp3" => "Native speakers are always exempted from the exams in their own language.",
        "2018collection_33.mp3" => "While reconciliation is desirable, the basic underlying issue must be addressed.",
        "2018collection_34.mp3" => "The theme of the instrumental work exhibits a more demure, compositional style.",
        "2018collection_35.mp3" => "Participants are initially selected from a range of foundation subjects.",
        "2018collection_36.mp3" => "The untapped potential of using the sun is enormous.",
        "2018collection_37.mp3" => "Good research delivers practical benefits for real people.",
        "2018collection_38.mp3" => "Review all resources before drawing your conclusion.",
        "2018collection_39.mp3" => "Assignments should be submitted to the department before the deadline.",
        "2018collection_40.mp3" => "The undergraduates need some specific sources, to analyse a specific program.",
        "2018collection_41.mp3" => "If finance is the cause of concern, a scholarship will be available.",
        "2018collection_42.mp3" => "Clinical placement in nursing prepares students professional practice.",
        "2018collection_43.mp3" => "The library holds a substantial collection of materials in economic history.",
        "2018collection_44.mp3" => "It is hard to anticipate all the different characters that were in the act.",
        "2018collection_45.mp3" => "The city’s founder created a set of rules that became to law.",
        "2018collection_46.mp3" => "The placement test for mathematics and statistics is offered in this semester.",
        "2018collection_47.mp3" => "The museum is closed on the first Monday of each month.",
        "2018collection_48.mp3" => "Mutually exclusive events are neither complementary nor opposing.",
        "2018collection_49.mp3" => "The results of the study underscored the discoveries from early detections.",
        "2018collection_50.mp3" => "A typical task of this course involves a study of society.",
        "2018collection_51.mp3" => "We can't consider an increase in the price at this stage.",
        "2018collection_52.mp3" => "The artists tied the conservative politicians, earned their roles of critics.",
        "2018collection_53.mp3" => "Radio is a popular form of entertainment throughout the world.",
        "2018collection_54.mp3" => "The ways in which people communicate are constantly changing.",
        "2018collection_55.mp3" => "The commissioner will portion a fund among the authorities.",
        "2018collection_56.mp3" => "Tribes vibe with each other to build monolithic statues.",
        "2018collection_57.mp3" => "The summer course has been cancelled due to insufficient enrolment.",
        "2018collection_58.mp3" => "The two variables in the study were very closely correlated.",
        "2018collection_59.mp3" => "The sociology department is highly regarded worldwide.",
        "2018collection_60.mp3" => "There is a welcome party for all new students each term.",
        "2018collection_61.mp3" => "The plight of wildlife has been ignored by many developers.",
        "2018collection_62.mp3" => "The teacher asked the group to commence the task.",
        "2018collection_63.mp3" => "The nation achieved its prosperity by opening its port for trade.",
        "2018collection_64.mp3" => "Railway made long distance travel possible for everyone.",
        "2018collection_65.mp3" => "Assignments should be submitted to the department before the deadline.",
        "2018collection_66.mp3" => "Graduates from journalism get jobs in communications field.",
        "2018collection_67.mp3" => "The new media has transformed the traditional, national boundaries.",
        "2018collection_68.mp3" => "If finance is the cause of concern, a scholarship will be available.",
        "2018collection_69.mp3" => "An archaeologist’s new discovery stands out in previous overlooked foundations. ",
        "2018collection_70.mp3" => "We study science to understand, and appreciate the world around us.",
        "2018collection_71.mp3" => "The scientists are always asking the government for more money.",
        "2018collection_72.mp3" => "The history of this university is long and interesting.",
        "2018collection_73.mp3" => "Important details are missing from the summary.",
        "2018collection_74.mp3" => "The development in information technology has greatly changed the way people work.",
        "2018collection_75.mp3" => "Tours operate all year around, but the busiest dry season runs from May.",
        "2018collection_76.mp3" => "There are still many people struggling in the lab.",
        "2018collection_77.mp3" => "Supply and demand is one of the most fundamental factors in the academic economics. ",
        "2018collection_78.mp3" => "You may need to purchase an academic gown before the commencement.",
        "2018collection_79.mp3" => "Chemistry building is located at the entrance to the campus.",
        "2018collection_80.mp3" => "The article illustrates a number of very interesting experiments. ",
        "2018collection_81.mp3" => "It might not be possible to solve the problem easily.",
        "2018collection_82.mp3" => "A celebrated theory is still a great source of controversy.",
        "2018collection_83.mp3" => "Animals raised in captivity behave differently from their wild counterparts.",
        "2018collection_84.mp3" => "Climate change is an accepted theory among a group of reputable scientists.",
        "2018collection_85.mp3" => "You can contact all your tutors by email.",
        "2018collection_86.mp3" => "Teaching assistants will receive a monthly stipend for housing.",
        "2018collection_87.mp3" => "Calculators may not be used during the examination.",
        "2018collection_88.mp3" => "All evaluation papers are reviewed by the university personnel.",
        "2018collection_89.mp3" => "When workers ask for higher wages, the companies often raise prices.",
        "2018collection_90.mp3" => "The study of archaeology requires extensive international field work.",
        "2018collection_91.mp3" => "The same issue featured both explanations of the problem.",
        "2018collection_92.mp3" => "Art is an expression of creative skill and imagination.",
        "2018collection_93.mp3" => "You must be able to work in a team.",
        "2018collection_94.mp3" => "Undergraduate students may pay their interest within specific programs.",
        "2018collection_95.mp3" => "He landed his job in a prestigious law firm.",
        "2018collection_96.mp3" => "All evaluation forms will be reviewed by the university personnel.",
        "2018collection_97.mp3" => "They were struggling last year to make their services paid.",
        "2018collection_98.mp3" => "Control systems in manufacturing require a high level of accuracy.",
        "2018collection_99.mp3" => "There is a pharmacy on campus near the bookstore.",
        "Educatio_1_.mp3" => "Education and training provide important skills for the labor force.",
        "Educatio_2_.mp3" => "Essential textbooks can be purchased from the campus bookshop.",
        "Educatio_3_.mp3" => "Every student has the right and ability to succeed.",
        "Educatio_4_.mp3" => "Exercise reduces the risk of morbid obesity.",
        "Educatio_5_.mp3" => "Good research paper delivers practical benefits to real people.",
        "Educatio_6_.mp3" => "I thought it was through the small meeting room.",
        "Educatio_7_.mp3" => "I will now demonstrate how the reaction can be arrested by adding a dilute acid.",
        "Educatio_8_.mp3" => "Lectures are the oldest and the most formal teaching method at universities.",
        "Educatio_9_.mp3" => "Majority of our decisions are not rational.",
        "Educatio_10_.mp3" => "NASA has been at the forefront of deep space exploration.",
        "Educatio_11_.mp3" => "Observers waited nervously with bated breath for the concert.",
        "Educatio_12_.mp3" => "Organic food is considered to be free of chemicals.",
        "Educatio_13_.mp3" => "Our medical school students must attend the talk about optional courses.",
        "Educatio_14_.mp3" => "Our professor is hosting the business development conference next week.",
        "Educatio_15_.mp3" => "Popular culture is a serious subject of academic inquiry.",
        "Educatio_16_.mp3" => "Practicing time-restricted eating a few times a week can be both feasible and healthy.",
        "Educatio_17_.mp3" => "Read the student instructions before using any equipment in the workshop",
        "Educatio_18_.mp3" => "Several organizations work to prevent animal cruelty.",
        "Educatio_19_.mp3" => "Some departments have their own special book collections.",
        "Educatio_20_.mp3" => "Some people are motivated by competition, while others prefer collaboration.",
        "Educatio_21_.mp3" => "Some young people find city life rather stressful.",
        "Educatio_22_.mp3" => "Students are advised to use multiple methods for this project.",
        "Educatio_23_.mp3" => "Students are required to use research methods for this project.",
        "Educatio_24_.mp3" => "Students who are successful have a good strategy for learning.",
        "Educatio_25_.mp3" => "Students will focus on reporting news on changing media world.",
        "Educatio_26_.mp3" => "The application process may take longer than expected.",
        "Educatio_27_.mp3" => "The article first introduces various interesting experiments.",
        "Educatio_28_.mp3" => "The assessment of this course will begin next week.",
        "Educatio_29_.mp3" => "The bar chart provides useful means of data comparison.",
        "Educatio_30_.mp3" => "The camera can identify eyes and focus on them.",
        "Educatio_31_.mp3" => "The commissioner will portion the funds among other authorities.",
        "Educatio_32_.mp3" => "The course has been updated to reflect the current situation.",
        "Educatio_33_.mp3" => "The course will help students to improve their pronunciation skills.",
        "Educatio_34_.mp3" => "The courses cover the several aspects of the subject.",
        "Educatio_35_.mp3" => "The department has a higher proportion of postgraduate students.",
        "Educatio_36_.mp3" => "The department has higher than normal proportion of postgraduate students.",
        "Educatio_37_.mp3" => "The designers will complete the plan later today.",
        "Educatio_38_.mp3" => "The economy is now on its first signs of recovery.",
        "Educatio_39_.mp3" => "The economy is showing signs of revival.",
        "Educatio_40_.mp3" => "The economy now is showing the first sign of recovery.",
        "Educatio_41_.mp3" => "The essay contains most of the important information.",
        "Educatio_42_.mp3" => "The history of this university is a long and interesting one.",
        "Educatio_43_.mp3" => "The new paper challenged the previously accepted theories.",
        "Educatio_44_.mp3" => "The new theory takes all the latest research results into account.",
        "Educatio_45_.mp3" => "The office will be closed during the Christmas break.",
        "Educatio_46_.mp3" => "The poster of this play is hung in the large hall.",
        "Educatio_47_.mp3" => "The professor took a year off to work on her book.",
        "Educatio_48_.mp3" => "The rising temperature is changing the wildlife population.",
        "Educatio_49_.mp3" => "The scientists use the web to explore the problems.",
        "Educatio_50_.mp3" => "The site is designed to be interactive.",
        "Educatio_51_.mp3" => "The timetable for the new term will be available next week.",
        "Educatio_52_.mp3" => "There are new innovations in the field of digital architecture.",
        "Educatio_53_.mp3" => "There is a clear need for further research in this field.",
        "Educatio_54_.mp3" => "This camera can identify eyes and focus on them.",
        "Educatio_55_.mp3" => "Undergraduates need some specific sources to analyse a program.",
        "Educatio_56_.mp3" => "Undergraduates pursue their interests in special stages within the program.",
        "Educatio_57_.mp3" => "We can work together to achieve the higher educational standards.",
        "Educatio_58_.mp3" => "We have not yet achieved equality in our society.",
        "Educatio_59_.mp3" => "Weather patterns have changed significantly over the past two hundred years.",
        "Educatio_60_.mp3" => "While reconciliation is desirable, basic underlying issues must first be addressed.",
        "Educatio_61_.mp3" => "You can request library books by using the electronic catalogue.",
        "Educatio_62_.mp3" => "You should draw your graph on a separate page.",
        "Educatio_63_.mp3" => "You should submit your team papers to the general office.",
        "Educatio_64_.mp3" => "You will acquire many skills during the academic studies.",
        "Library_1_.mp3" => "Library reference desks hold a lot of materials on academic history.",
        "Library_2_.mp3" => "Most of these features were part of the previous system.",
        "Library_3_.mp3" => "One of the election promises is to decrease the income tax.",
        "Library_4_.mp3" => "One of the promises is to decrease the contest.",
        "Library_5_.mp3" => "Plants and living things are growing on the land or in water.",
        "Library_6_.mp3" => "Plants are living things that grow on land and in water.",
        "Library_7_.mp3" => "Remember, the prestigious selection has strict eligibility criteria.",
        "Library_8_.mp3" => "Science is found in society all around the world.",
        "Library_9_.mp3" => "Scientists learned through the observations and the analysis of the human behaviour.",
        "Library_10_.mp3" => "Sea levels are expected to rise during the next century.",
        "Library_11_.mp3" => "She received a scholarship from the state library.",
        "Library_12_.mp3" => "Some people are motivated by competition while others prefer to collaborate.",
        "Library_13_.mp3" => "Some people believe that education should be free for all.",
        "Library_14_.mp3" => "Students are encouraged to monitor their own attendance.",
        "Library_15_.mp3" => "Students are encouraged to think carefully about their accommodation needs.",
        "Library_16_.mp3" => "Students should have an awareness of how the business develops globally.",
        "Library_17_.mp3" => "Students should have awareness of how the business develops globally.",
        "Library_18_.mp3" => "Studies show there is a positive correlation between two variables.",
        "Library_19_.mp3" => "The ability to work with fellow students cannot be stressed enough.",
        "Library_20_.mp3" => "The architectural numbers vary in that experiment.",
        "Library_21_.mp3" => "The artists and conservative politicians earn their rule of politics.",
        "Library_22_.mp3" => "The assessment of this course will begin next week",
        "Library_23_.mp3" => "The business class can hole with local students.",
        "Library_24_.mp3" => "A cafeteria features sandwiches, salads, soup, fish and chicken.",
        "Library_25_.mp3" => "The features issued the same explanation of the problem.",
        "Library_26_.mp3" => "The introduction is an essential element of presentation.",
        "Library_27_.mp3" => "The introduction is an important component of a good presentation.",
        "Library_28_.mp3" => "The library holds a substantial collection of materials on Economic History.",
        "Library_29_.mp3" => "The main concepts in this thesis were not new.",
        "Library_30_.mp3" => "The marketing budget is doubled since the beginning of the year.",
        "Library_31_.mp3" => "The office opens on Mondays and Thursdays directly follow the freshman categories.",
        "Library_32_.mp3" => "The results of the study underscored the discoveries from early detection.",
        "Library_33_.mp3" => "The same approach reached to the same explanation of the problem.",
        "Library_34_.mp3" => "The same issue featured both explanations of the problem.",
        "Library_35_.mp3" => "The site is designed to be highly interactive.",
        "Library_36_.mp3" => "The summer course has been cancelled due to insufficient enrolment.",
        "Library_37_.mp3" => "The summer course was cancelled due to insufficient re-enrolments.",
        "Library_38_.mp3" => "The teaching group will be performing in the concert hall.",
        "Library_39_.mp3" => "The two variables in the study were very closely correlated.",
        "Library_40_.mp3" => "The undergraduates need some specific sources to analyse a program.",
        "Library_41_.mp3" => "There are many types of governments in the world.",
        "Library_42_.mp3" => "There is a pharmacy on campus near the bookstore.",
        "Library_43_.mp3" => "There is a welcome party for all new students each term.",
        "Library_44_.mp3" => "There is clearly a need for further research in this field.",
        "Library_45_.mp3" => "There is welcome party for all new students each term.",
        "Library_46_.mp3" => "There was a prize for the best student of the presentation.",
        "Library_47_.mp3" => "This course provides the opportunity to get valuable industry experience.",
        "Library_48_.mp3" => "Those who are considering a career of marketing should attend the talk.",
        "Library_49_.mp3" => "Timetable about new time will be available next week.",
        "Library_50_.mp3" => "Tribes vibe with each other to build monolithic statues.",
        "Library_51_.mp3" => "University fees are expected to increase next year.",
        "Library_52_.mp3" => "P can work together to achieve the higher educational standards.",
        "Library_53_.mp3" => "We have not achieved the equality in our society.",
        "Library_54_.mp3" => "We support to do research in the field of archaeology such as forecasting and estimation.",
        "Library_55_.mp3" => "You can use a laptop during the lecture.",
        "Library_56_.mp3" => "You will acquire new skills during your academic studies.",
        "Library_57_.mp3" => "A good academic paper should be clear.",
        "Library_58_.mp3" => "A good assistance is not afraid to ask questions.",
        "Library_59_.mp3" => "Accountancy students probably have a good understanding of economics, statistics and psychology.",
        "Library_60_.mp3" => "Accountant students should have a good understanding of profit and loss statement.",
        "Library_61_.mp3" => "All lectures and learning materials can be found on the internet.",
        "Library_62_.mp3" => "Atmosphere is composed of several layers.",
        "Library_63_.mp3" => "Bad policy decisions led to the financial crisis.",
        "Library_64_.mp3" => "Behind the garage is a secret storage room.",
        "Library_65_.mp3" => "Building trust is not something that can be achieved overnight.",
        "Library_66_.mp3" => "Cell is the most basic building block for all animals and plants.",
        "Library_67_.mp3" => "Cinema and music are as important as science and mathematics.",
        "Library_68_.mp3" => "Click the logo above to enter the site.",
        "Library_69_.mp3" => "Coursework and exams will form part of the annual assessment.",
        "Library_70_.mp3" => "Despite the differences, all forms of lives share the same characteristics.",
        "longwfd_1.wav" => "All industries are thought as systems as  inputs, processes, outputs and feedback.",
        "longwfd_2.wav" => "An Archaeologist’s new discovery stands out in previously overlooked foundations.",
        "longwfd_3.wav" => "Another common mistake is to ignore or rule out data which do not support the hypothesis.",
        "longwfd_4.wav" => "Ideally, the experiment is opened to the possibility that the hypothesis is correct or incorrect.",
        "longwfd_5.wav" => "In consultation with your supervisor, your thesis is approved by faculty committee.",
        "longwfd_6.wav" => "Many students are so scare of writing essays because they never learned how.",
        "longwfd_7.wav" => "Rivers provide habitats and migration pathways to fish and numerous aquatic species.",
        "longwfd_8.wav" => "The artists tied the conservative politicians earned their roles in critics.",
        "longwfd_9.wav" => "The business development seminar includes some entrepreneurships into the local firm.",
        "longwfd_10.wav" => "The elective course introduces engineering students to construct practices and concepts.",
        "longwfd_11.wav" => "The glimpse of dipping into this as a hobby is an enormously rewarding experience.",
        "longwfd_12.wav" => "This science fiction novel uses invention for better space to create the setting.",
        "longwfd_13.wav" => "Undergraduates may pay their interests on the specific stages within specific programs.",
        "longwfd_14.wav" => "The development in information technology has greatly changed the way people work.",
        "longwfd_15.wav" => "Please note the submission deadlines are only negociable in exceptional circumstance.",
        "longwfd_16.wav" => "Native speakers are examined their language tests by their own languages.",
        "longwfd_17.wav" => "It is the words of common occurrence that have different referential value.",
        "longwfd_18.wav" => "The dance department stages elaborated performances each semester.",
        "longwfd_19.wav" => "Rising inflation will increase the demand, price and the consumption of products.",
        "longwfd_20.wav" => "They look at the health needs of the local community and develop the plans to set up priorities locally.",
        "longwfd_21.wav" => "Life expectancy and infant mortality rates are two of the best indicators of overall health.",
        "longwfd_22.wav" => "Even if you have used cosmetic for years without problem, one or more ingredients can still trigger allergic reaction.",
        "longwfd_23.wav" => "Our food supply now contains so much added sugar that our metabolic system can not handle it.",
        "longwfd_24.wav" => "Hundreds of millions of dollars are spent each year to promote unhealthy foods.",
        "longwfd_25.wav" => "When everyone commits to looking after their health, soft drinks will not be on the menu.",
        "longwfd_26.wav" => "Practicing time restricted eating a few time a week could be both feasible and healthy.",
        "longwfd_27.wav" => "Cosmetics and plastic surgery often evokes images of famous personalities.",
        "longwfd_28.wav" => "The leading companies have changed their policies and procedures after their reports were released.",
        "longwfd_29.wav" => "Student concession cards need to be obtained to completing an application form.",
        "longwfd_30.wav" => "Higher numbers of patients were affected during our break of the previous illness.",
        "longwfd_31.wav" => "There will be a conference here next summer on using the web for academic research.",
        "longwfd_32.wav" => "Americans have cheapest typical growth in quantitative of terms.",
        "longwfd_33.wav" => "Americans have progressively defined the process of plant growth and reproductive.",
        "longwfd_34.wav" => "The author’s early work is more philosophical and less experimental.",
        "longwfd_35.wav" => "The commission will be pooled into funds among the authorities.",
        "longwfd_36.wav" => "It is really a comprehensive program that covers both theory and practice.",
        "longwfd_37.wav" => "Animals raise in captivity behave differently from their wild counterparts.",
        "longwfd_38.wav" => "Those students seeking for formal extension should talk to their faculties for more information.",
        "longwfd_39.wav" => "Submitting for your group assignments should be punctually issued by one of your group members.",
        "longwfd_40.wav" => "While reconciliation is desirable, the basic underlying issue must first be addressed.",
        "longwfd_41.wav" => "When bad drove out good, the local workers were more difficult than their competitors.",
        "longwfd_42.wav" => "The fertile plains in the east of the regions provide the excellent land for farming.",
        "longwfd_43.wav" => "The theme of the workshop is more of a demure, compositional style.",
        "longwfd_44.wav" => "Organizational failure is considered as various perspectives of academic literature.",
        "longwfd_45.wav" => "The findings of the researchers are focused on the causes of the diseases in treatments.",
        "longwfd_46.wav" => "Affordable housing is an important issue for all members of society.",
        "longwfd_47.wav" => "Climate change is becoming an acceptable phenomenon amongst a group of reputable scientists.",
        "longwfd_48.wav" => "The module of the work is more of a compositional style.",
        "longwfd_49.wav" => "And in that regard, as well as other regards, it stands as an important contribution.",
        "longwfd_50.wav" => "Some people regarded as eye wash whereas some people ask for the status of their complaints and actions taken.",
        "longwfd_51.wav" => "Public perception about  biotechnology is crucial for developing scientific consensus.",
        "longwfd_52.wav" => "The massive accumulation data is converted into the communicable arguments.",
        "longwfd_53.wav" => "Before submitting your dissertation registration, your advisor must approve your application.",
        "longwfd_54.wav" => "Law is beneficial to investors by protecting their rights and avoiding any improper actions in the market.",
        "longwfd_55.wav" => "Applicants for this course preferably have a preference over English and journalism.",
        "longwfd_56.wav" => "They look at the health needs of the local community and develop plans to set priorities locally.",
        "longwfd_57.wav" => "Life expectancy and infant mortality rates are two of the best indicators of overall health."
      }

# Database for Read Aloud Skills
#  Example: read_aloud = [" ", " ", ...]
read_aloud_easy = ["Computers which are capable of teaching themselves to predict premature death could greatly improve preventative healthcare in the future, a new study suggests.",
		   "A synaesthesia-like effect in which people 'hear' silent flashes or movement, such as in popular 'noisy GIFs' and memes, could be due to a reduction of inhibition of signals that travel between visual and auditory areas of the brain, according to a new study. It was also found that musicians taking part in the study were significantly more likely to report experiencing visual ear than non-musician participants.",
		   "To arrive at this destination, we had to take a ferry from the mainland, a journey which lasted roughly one hour.",
		   "Last summer, my family went on a vacation to Cat Ba island, which is located in Hai Phong city and I was really impressed with the beach.",
		   "Biophysicists have used an automated method to model a living system -- the dynamics of a worm perceiving and escaping pain. The model makes accurate predictions about the dynamics of the worm behavior, and these predictions are biologically interpretable and have been experimentally verified.",
		   "Researchers have found a new way to make cathodes for lithium batteries, offering improvements in the amount of power for both a given weight and a given volume.",
		   "New research suggests that deep groundwater could still be active on Mars and could originate surface streams in some near-equatorial areas on Mars.",
		   "One important requirement to see quantum effects is to remove all thermal energy from the particle motion, i.e. to cool it as close as possible to absolute zero temperature. Researchers are now one step closer to reaching this goal by demonstrating a new method for cooling levitated nanoparticles.",
		   "An enzyme-blocking molecule can extend the lifespan of Caenorhabditis elegans roundworms by as much as 45 percent, largely by modulating a cannabinoid biological pathway, according to a new study.",
		   "A woman in Scotland can feel virtually no pain due to a mutation in a previously-unidentified gene, according to a research article. She also experiences very little anxiety and fear, and may have enhanced wound healing due to the mutation, which the researchers say could help guide new treatments for a range of conditions."
                  ]

read_aloud_hard = ["Thompson recognized and exploited all the ingredients of a successful amusement ride,” write Judith A. Adams in the American Amusement Park Industry. “His coasters combined an appearance of danger with actual safety, thrilled riders with exhilarating speed, and allowed the public to intimately experience the Industrial Revolution’s new technologies of gears, steel, and dazzling electric lights.",
		   "Over the centuries, the holiday evolved, and by the 18th century, gift-giving and exchanging handmade cards on Valentine’s Day had become common in England. Handmade Valentine’s cards made of lace, ribbons, and featuring cupids and hearts eventually spread to the American colonies. The tradition of Valentine’s cards did not become widespread in the United States, however, until the 1850s.",
		   "Although Botswana’s economic outlook remains strong, the devastation that AIDS has caused threatens to destroy the country’s future. In 2001, Botswana has the highest rate of HIV infection in the world. With the help of international donors it launched an ambitious national campaign that provided free antiviral drugs to anyone who needed them, and by March 2004, Botswana’s infection rate has dropped significantly.",
		   "Global warming is deﬁned as an increase in the average temperature of the earth's atmosphere. This trend began in the middle of the 20th century and is one of the major environmental concerns of scientists and governmental ofﬁcials worldwide. The changes in temperature result mostly from the effect of increased concentrations of greenhouse gasses in the atmosphere.",
		   "In the photo, the wild cat‘s huge paws are clamped onto the side of the white safari Jeep in which Chappell was a passenger. Almost as tall as the Jeep on her hind legs, she appears to be forcing her muzzle into the back window.",
		   "Who do you think is the most glamorous person? A biotechnologist who led his company in international research, an ordinary welder who gained international fame through his work, or a photographer complimented widely for a series of photos?",
		   "This ﬁnding is understandable in certain cases in spite of its high significance; that is because energy efﬁciency of building operation just represents a single aspect of sustainability.",
		   "Three professors from Hamburg University's medical faculty travelled last month to Ingeborg's sitting room in East Berlin to test her on the work she carried out in pre-war Germany.",
		   "Akimbo, this must be one of the odder—looking words in the language and puzzles us in part because it doesn’t seem to have any relatives. What‘s more, it is now virtually a fossil word, until recently almost invariably found in arms akimbo, a posture in which a person stands with hands on hips and elbows sharply bent outward, one that signals impatience, hostility or contempt.",
		   "New research suggests that environmental contaminants found in the home and diet have the same adverse effects on male fertility in both humans and in domestic dogs. There has been increasing concern over declining human male fertility in recent decades with studies showing a 50 global reduction in sperm quality in the past 80 years.",
                   "The Office of Personnel Management was the target of the attack, but data from nearly every government agency was stolen. U.S. investigators say they believe Chinese hackers were behind the breach.",
                   "Global warming is defined as an increase in the average temperature of the earth's atmosphere. This trend began in the middle of the 20th century and is one of the major environmental concerns of scientists and governmental officials worldwide. The changes in temperature result mostly from the effect of increased concentrations of greenhouse gasses in the atmosphere.",
                   "As far as politics go, the responses are just as varied. Mitigation is common and calls for a reduction of emissions and less reliance on fossil fuels. Coal burning power plants are now replaced with hydraulic power plants and electrical cars are replacing some gasoline efficient cars. Many people, however, feel that this is not enough.",
                   "The border itself between Mexico and United States is fraught with a mix of urban and desert terrain and spans over 1900 miles. Both the uninhabited areas of the border and urban areas are where the most drug trafficking and illegal crossings take place. Crime is prevalent in urban cities like El Paso, Texas and San Diego, California.",
                   "Free trade is an economic policy under which the government does not interfere with trade. No tariffs are applied to imports or exports, and people are allowed to trade goods and services as they please. Supply and demand dictates the prices for which goods and services sell and are the only factors that determine how resources are allocated in society.",
                   "Unlike the United Kingdom, which has taken a relatively restrictive approach to the possession of arms, the United States has taken a more lenient approach. In the United States, three models have evolved regarding the interpretation of the meaning of the right to bear and keep arms as delineated in the Second Amendment.",
                   "Trade unions originated in Europe during the industrial revolution. Because of the machinery that had become commonplace, skilled labor became less in demand so employers had nearly all of the bargaining power. Employers mistreated the workers and paid them too little for the work they did. Trade unions were organized that would help in the improvement of working conditions.",
                   "Unions take the power out of the employer's hands on many issues. There are examples of cases where workers were engaging in sexual or racial harassment, but were protected by their unions and allowed to keep their jobs. Poor workers and excellent workers often receive the same pay and raises, giving no reason for a person to work harder than necessary at their job.",
                   "Another administration option is to bake marijuana at a relatively low temperature to kill any dangerous microorganisms and then allow that patient to eat it or drink it. Both of these methods of administration make smoking the drug unnecessary. However, criticism of medical marijuana has also been raised because as a natural plant, it cannot be patented and marketed by pharmaceutical companies and is unlikely to win widespread medical acceptance.",
                   "Smoking ban is a public policy that includes criminal laws and health regulations that prohibit smoking in certain public places and workspaces. There are varying definitions of smoking employed in this legislation. The strictest definitions define smoking as being the inhalation of any tobacco substance while the loosest define smoking as possessing any lit tobacco product.",
                   "Welfare has a special political meaning to the United States because it refers to how the poor receives financial aid. In comparison, welfare services are regarded as a universal right in other regions like Europe, where it is believed that all citizens should be able to obtain a minimal level of social support and well-being.",
                   "We acknowledge all the information and memory notes provided by students. We also acknowledge open source from various books and journal articles. All questions and answers are prepared and annotated by the Australian Institute of Language. All rights reserved. Not for any commercial purposes, for personal study only.",
                   "We have attempted to provide as accurate information as possible to assist all students with the exam preparation. Please note, however, that due to the accuracy of the memory, there may be subtle differences in words and phrases. When in actual exams, please carefully read the questions before using any of the sample answers.",
                   "Yellow is the most optimistic color, yet surprisingly, people lose their tempers most often in yellow rooms and babies cry more in them. The reason may be that yellow is the hardest color on the eye. On the other hand, it speeds metabolism and enhances concentration; think of yellow legal pads and post-it notes.",
                   "Cheerful sunny yellow is an attention getter. While it is considered an optimistic color, people lose their tempers more often in yellow rooms, and babies will cry more. It is the most difficult color for the eye to take in, so it can be overpowering if overused. Yellow enhances concentration, hence its use for legal pads. It also speeds metabolism.",
                   "Since Plato, philosophers have described the decision-making process as either rational or emotional: we carefully deliberate or we “blink” and go with our gut. But as scientists break open the mind’s black box with the latest tools of neuroscience, they’re discovering that this not how the mind works. Our best decisions are a finely tuned blend of both feeling and reason - and the precise mix depends on the situation.",
                   "Moods may also have an effect on how information is processed, by influencing the extent to which judges rely on pre-existing, internal information, or focus on new external information. Positive moods promote more holistic and top-down processing style, while negative moods recruit more stimulus – driven and bottom- up processing.",
                   "The brain is divided into two hemispheres, called the left and right hemispheres. Each hemisphere provided a different set of functions, behaviors, and controls. The right hemisphere is often called the creative side of the brain, while the left hemisphere is the logical or analytical side of brain.",
                   "Introverts (or those of us with introverted tendencies) tend to recharge by spending time alone. They lose energy from being around people for long periods of time, particularly large crowds. Extroverts, on the other hand, gain energy from other people. Extroverts actually find their energy is sapped when they spend too much time alone. They recharge by being social.",
                   "A young man from a small provincial town - a man without independent wealth, without powerful family connection and without a university education - moved to London in the late 1580’s and, in a remarkably short time, became the greatest playwright not of his age alone but of all time. How did Shakespeare become Shakespeare?",
                   "Botanic gardens are scientific and cultural institutions established to collect, study, exchange and display plants for research and for the education and enjoyment of the public. There are major botanic gardens in each capital city. Zoological parks and aquariums are primarily engaged in the breeding, preservation, study and display of native and exotic fauna in captivity.",
                   "Although introvert and extrovert personality types differ from one another on various grounds, the major difference between the two is their source of rejuvenation. While for extroverts, this may mean interaction or excursions with friends and family, the same may mean reading a book or listening to music for introverts.",
                   "In the fast-changing world of modern healthcare, the job of a doctor is more and more like the job of a chief executive. The people who run hospitals and physicians’ practices don’t just need to know medicine. They must also be able to balance budgets, motivate a large and diverse staff and make difficult marketing and legal decisions.",
                   "All cells share some common characteristics that make them living things. All organisms are composed of cells, the basic fundamental unit of life. They contain DNA as a heritable genetic material, and they can reproduce. They transcribe DNA into RNA and translate RNA into proteins on ribosomes. They can also regulate transport across a cell membrane and require chemical energy for some cellular processes.",
                   "The number one biggest difference between the bacteria in your body and the cells making up your body are these tiny cellular components called organelles. You've actually learned a lot about organelles in other lessons without knowing it. Organelles are simply membrane-bound compartments within a cell, such as the nucleus, mitochondria, chloroplasts, golgi, and endoplasmic reticulum.",
                   "In the second quarter of the 19th century, a rapidly growing middle class created a great demand for furniture production. Yet at this stage, while machines were used for certain jobs, such as carved decoration, there was no real mass production. The extra demand was met by numerous woodworkers. Mass Production came later and the quality of domestic furniture declined.",
                   "'There are, of course, intercultural difficulties as well as language difficulties,' he said. 'There are, of course, also many Australian students who don't speak such fantastically good English either.'",
		   "'I've seen no evidence to suggest that students are not able to complete their courses because they're failing in English yet they're being passed by the universities,' she said. 'I've not seen any evidence to back that up.” International education is one of our largest exports, it's our fourth largest export and it's in the interest of our universities to maintain very high standards because their reputation is at stake.'",
		   "Solar energy is an excellent source of supplying power to homes and companies and by utilizing solar power you're not merely protecting the environment from becoming polluted but also you are saving the rest of the earth's natural resources. Capturing solar energy does not contribute any pollution and does not harm the atmosphere. One of the factors why many individuals are still hesitant to make use of solar power is because it is expensive. The need of big location of space is another reason why people aren't taking into consideration solar power.",
		   "Living room is the most used part that withholds most of the traffic coming in and out of the house. It is highly recommended that the flooring should be strong enough that it can endure all such amendments done with your furniture or to the increasing and decreasing ratio of visitors. For this purpose you can opt for hardwood flooring. Being classy and sophisticated in look it is the perfect choice for your living room whenever you are remodeling your home.",
		   "If you do experience a motorcycle crash, be aware the other driver will most likely blame you for the accident. This includes the road, road conditions, any skid marks, road signs, construction, and anything else that may have contributed to the accident. Not every accident requires an attorney but a knowledgeable local attorney can help you make sense of the process, as well as insure that the other drivers insurance doesn't unfairly blame you for the accident.",
		   "Many people are under the impression that the water which comes out of a plant is clean. This is a common misconception: the function of a plant is to make the water cleaner, but it's not clean enough to drink. It could be used in irrigation. What a plant is trying to do is to simply speed up a process which would naturally occur given more time. This means that a plant can create water which is safe to enter back into the water system as it's so heavily diluted. The river then continues the water purification, acting as a form of fourth stage.",
		   "Another virtue that both propagate is that the present is meant to be enjoyed to the fullest. It is no use fretting about the past for it cannot be undone or overturned and no use pondering too much, about the future for it remains unseen. The day being thought about may never dawn on you. The ultimate service, however, remains the one done for your fellow men.",
		   "The Ford Company provides plenty of opportunities for its employees. It guarantees not only comfortable and appropriate working conditions, but also many other advantages. Therefore, becoming a part of the Ford Motor company is always profitable and beneficial. Moreover, it is important to mention that Ford Motors provides its employees with effective and useful services and takes care of their well-being.",
		   "On practice, M. Kent tries to develop a worldwide campaign in order to expand the scope of activities and invite new customers. He tries to spread the Coca-Cola production throughout the globe in order to achieve a good place on the global market. Moreover, he always pays attention to the work of the competitors in order to remain on top. Finally, M. Kent knows how to organize the work within the company and motivate employees to do their best.",
		   "The southerners did not accept Lincoln as a president because of certain reasons, based on historical grounds. Southerners wished to protect their rights in the government and become more independent from the north. They considered president elections to be unfair. Moreover, they thought that their own rights will be ignored and limited. All this caused the separation of the southern states and marked the beginning of the Civil War.",
		   "Therefore, the working unions in modern society are not very important. They preserve their functions only in the underdeveloped countries. On the contrary, in the developed states, workers refuse to join the unions, preferring individual work. Thus, working unions cannot survive the assault of modern economic trends and slowly move to a complete decline. Their initial purposes have little to do with the hectic pace of modern life.",
		   "The most important issue is concerned with the problem of funding. Social services receive different donations or grants from the government. However, these sums are not sufficient for the solution of all problems. The second most important issue consists in the huge spending. The money social services achieve, is not enough for normal functioning. The third problem, affecting human services is the lack of skilled and experienced employees.",
		   "The asteroid that slammed into the moon 3.8 billion years ago creating the Imbrium Basin may have had a diameter of at least 150 miles, according to a new estimate. The work helps explain puzzling geological features on the moon's near side, and has implications for understanding the evolution of the early solar system.",
		   "For any marketing course that requires development of marketing plan, such as marketing management, marketing strategy and segmentation support marketing, this is the only planning handbook that guide students through the step by step creation of customized marketing plan. While offering commercial software to aid in the process.",
		   "As we progress into the 21st century, communications are becoming faster and faster and faster. Think of the millions of different media images you are bombarded with every day. It is as important now to be able to read and make sense of those images, as it has been to be able to read ordinary text.",
		   "Electronic discourse is one form of interactive electronic communication. In this study, we reserve the term for the two-directional texts in which one person using a keyboard writes language that appears on the sender's monitor and is transmitted to the monitor of a recipient, who responds by keyboard.",
		   "Although it hails from a remote region of the western Himalayas, this plant now looks entirely at home on the banks of English rivers. Brought to the UK in 1839, it quickly escaped colonized river banks and damp woodlands. Now it is spreading across Europe, New Zealand, and Canada. In the Himalayas the plant is held in check by various pests, but take these away and it grows and reproduces unhindered.",
		   "The quest for a user-friendly copyright regime began a decade ago when the Hong Kong government launched a public consultation on “Copyright Protection in the Digital Environment” in December 2006. Although this consultation initially sought to address Internet-related challenges, such as those caused by peer-to-peer file-sharing technology, the reform effort quickly evolved into a more comprehensive digital upgrade of the Hong Kong copyright regime.",
		   "How quickly is the world’s population growing? In the United States and other developed countries, the current growth rate is very low. In most developing countries, the human population is growing at 3 people per second. Because of this bustling growth rate, human population is grown to reach 9 billion within your lifetime.",
		   "Surprisingly, despite what appear to be infinite variations, all difficult conversations share a common structure. When you're caught up in the details and anxiety of a particular difficult conversation, this structure is hard to see. But understanding that structure is essential to improving how you handle your most challenging conversations.",
		   "It isn't rare for private equity houses to hire grads fresh out of business school, he said, but 9 times out of 10, the students who nab these jobs are the ones who had private equity experience under their belt before even starting their MBA program.",
		   "The founding fathers established constitutional protections for the press because they understood that leaving the watchdog function to partisan politicians wouldn’t necessarily serve the public interest; both sides have too many incentives to preserve the status quo and ignore problems that elude quick fixes.",
		   "Weakness in electronics, auto and gas station sales dragged down overall retail sales last month, but excluding those three categories, retailers enjoyed healthy increases across the board, according to government figures released Wednesday. Moreover, December sales numbers were also revised higher.",
		   "Where there are effects, there are often side effects. The car is a boon to mobility, but can lead to obesity, injuries, deaths and pollution. Burning fossil fuel may keep economies going, but wrecks the climate in the long run. In a similar way, there are side effects to information technology in education settings – from childcare to the classroom to the lecture hall and beyond.",
		   "There are perhaps three ways of looking at furniture: some people see it as purely functional and useful, and don't bother themselves with aesthetics; others see it as essential to civilized living and concern themselves with design and how the furniture will look in a room - in other words, function combined with aesthetics; and yet others see furniture as a form of art.",
		   "Currently, Integration is increasingly needed in the business environment. This need emerges from the efficiency and synergy requirements necessary in a complex and turbulent environment. In other words, integration is needed to facilitate coordination, which is again related to the building of competitive advantage.",
		   "The English Revolution has been interpreted in several ways by historians: as a fight between the aristocratic Cavaliers, who were open to life, and the serious Puritans; as a battle for power between parliament and the monarchy over the rights of Englishmen that had been going on for centuries; and as a class war similar to the French Revolution, of which it was a forerunner.",
		   "A recent trend in the entertainment world is to adapt classic works of literature for either TV or movies. One argument is that this is to everyone’s benefit, as it introduces people to works they might otherwise never have, but is rarely done successfully.",
		   "A university is a lot more than just classes and exams, university is a concept that offers you a host of possibilities to develop both academically and personally. Find out about the different projects, clubs and societies that are in your university. You will definitely find something you are interested in.",
		   "Japan is the world’s calculator superpower. Japanese manufacturers have led sales of calculators for over thirty years in many countries. Even in the age of personal computers, calculators are still essential in accounting jobs. In addition, calculators with graphing capabilities have begun to be used in education.",
		   "Whether salamander frog or toad, amphibians are some of the most diverse and far-flung animals on the planet. However, they’re disappearing, and experts are worried since frogs are considered bellwethers for the environment. Their double life makes them unique. It’s through their skin that they breathe and drink water because their skin is so permeable.",
		   "The Executive Residence in The White House, in the United States of America, where the president resides is divided in several wings. It also includes the vice-president’s and president’s staff’s offices. This government building is a national heritage.",
		   "Cloud seeding, a form of weather modification, is a way of attempting to change the amount of precipitation that comes from clouds. Cloud seeding is carried out by dispersing substances into the air, but it also occurs due to ice nucleates in nature, most of which are bacterial in origin.",
		   "Many families are fleeing their native countries due to sectarian repression and political uprisings. Consequently, thousands of people have been stranded in foreign lands for months; other families have gone missing in the sea, marooned in small boats, as the neighboring foreign countries refuse to take them in.",
		   "Countries bordering the Mediterranean have built up a solid reputation for sunshine, great tasting food, as well as impressive health statistics, featuring some of the lowest rates of heart disease, and increased life expectancy. This has created a lot of attention towards the Mediterranean diet, which is not a typical weight loss diet, but more of a set of habits.",
		   "As a historian, if you really want to understand the sensibilities of those who lived in the past, you must be like a novelist and get into the skins of your characters and think and feel as they do. You are asked to imagine what it's like to be a peasant in medieval times, asking the sort of questions a peasant might ask. What the writer is saying is that a historian needs imaginative sympathy with ordinary people in the past.",
		   "Trump has threatened to declare China a currency manipulator, but experts say he has little legal or economic basis to take such a step. He has also threatened to impose a tariff of up to 45 percent on Chinese imports if Beijing doesn’t “behave” a move that could lead to a trade war and damage the economies of both nations.",
		   "Do something you are very passionate about and do not try to chase what is considered the hot passion of the day. People say you have to have a lot of passion for what you’re doing, and it’s totally true. You have to do it over a sustained period of time. So, if you don’t love it, you’re going to give up.",
		   "Charlie Parker noticed that the solos were only improvised through the melodies, but that he could also improvise them through the chords, thus creating new variations over the structure of the songs, and also playing more notes and faster.",
		   "The discovery of universal gravitation displays all the features of the new way of scientific reasoning which is now so familiar to us. The discovery starts off with Newton associating the Moon’s behavior with the behavior of rocks falling on the ground.",
		   "They controlled for the birds’ age, sex, body size and species. And they found that the hunted specimen’s brains were actually five percent smaller, on average, than the brains of birds that died by other means. “The surprising thing is that, if you make a smaller kind of analysis of liver or heart size, there is absolutely no difference there. So this is specific to the brain. ”",
		   "Generally, students who stay off campus resort to campus buses, for it not only costs less, but also helps reach the college campus on time. However, there are separate dormitories for students who wish to stay back in the campus for any activity.",
		   "Polar bears are born on land, but they spend most of their days’ time in the cold sea, enjoying swimming and hunting seals. Though aggressive in nature, they do not easily become pugnacious and defer their reactions as much as they can.",
		   "Straddling Asia and Europe across the strait, the old city of Istanbul, Turkey, has embraced diverse cultural influences. Known for its monumental architecture, Istanbul has become a cherished travel destination.",
		   "Any animals deprived of their basic sheltering, food, and health rights must be handed over to an NGO. After bringing them back to health, they can be put up for adoption, following substantial background check rules before providing them with new owners.",
		   "It was in 1927 when Mercedes Glitzed swam across the English Channel and Rolex became associated with excellence in the watch industry. She was wearing an Oyster wristwatch when she accomplished this achievement, fact that ignited the brand value of Rolex for uniting human spirit with endeavor.",
		   "The speaker is a marine biologist who became interested in the Strandlopers, an ancient people who lived on the coastline, because of their connection to the sea. Their way of life intrigued him. As a child he had spent a lot of time by the sea, exploring and collecting things – so he began to study them, and discovered some interesting information about their way of life, how they hunted, what tools they used, and so on.",
		   "Jazz is an African American music genre popular in the United States that has an enchanting effect on the young and intellectuals. Scintillating performances by many bands across the globe have also helped this music style become widely popular.",
		   "The Kepler spacecraft has found hundreds of planets and thousands of additional candidates. Exploration of our solar system leads to a view of planets that emphasizes diversity rather than similarity. However, with so many planets out there, yes, some must be like Earth.",
		   "Reiss took a stab at settling the argument with a meta-analysis — a study of studies — on whether people can really perceive better-than-CD quality sound. He analyzed data from 18 studies, including more than 400 participants and nearly 13,000 listening tests. Overall, listeners picked out the better-than-CD-quality track 52.3 percent of the time. Statistically significant, if not all that impressive.",
		   "Researchers gathered 160 un-caffeinated adults, people who consumed less than 500 milligrams of caffeine a week. These decaf subjects looked at pictures of various objects, then took either a placebo or a pill containing 200 milligrams of caffeine. That’s roughly the amount you’d get from two cups of coffee.",
		   "The term supernova was coined in the 1930s by a memorably odd astrophysicist named Fritz Zwicky. Born in Bulgaria and raised in Switzerland, Zwicky came to the California Institute of Technology in the 1920s and there as once distinguished himself by his abrasive personality and erratic talents. He didn’t seem to be outstandingly bright, and many of his colleagues considered him little more than “an irritating buffoon”",
		   "Rites of Passage are one deep avenue to experience this love in our bones. Once realized, the care for the earth, the connection and experience of nature, and our part and place in the whole, will inform our future, our care for all of life. Without this care, and a true understanding of interdependence, our actions and lives may well be fragmented, divisive, and destructive.",
		   "At the end of this year, we will launch the Cup Class boats. So these will be about twice the power. The sailors are down in cockpits, unlike today. A lot of the power is being generated by these four grinders that are providing hydraulic power, and that energy is being used to control the flying surface, the hydrofoil is also being used to control the wing and the flaps, effectively the engine, of what we have.",
		   "Kinder Mann says he thinks the compound could be a win-win for the planet and the animals. 'You know the methane is kind of a waste product. And this energy, instead of losing it for the animal, it can be reused for the animal in terms of performance, and at the same time we are doing something for greenhouse gas emission and climate change.' The products not on the market yet toxicology tests are ongoing.",
		   "What we found is that the plant is actually damaged by herbivores like most plants are in nature. And in response to that it secretes sugar from the wound edges where the herbivores have damaged the plant. Tobias Lortzing is a graduate student at Freie University Berlin and one of the study authors.",
		   "In meteorology, precipitation is any product of the condensation of atmospheric water vapor that falls under gravity. The main forms of precipitation include drizzle, rain, sleet, snow, graupel, and hail.",
		   "You may have heard of the new fad known as ecotourism. This means tourism which is environmentally friendly, and conscious about conserving the environment. The key is to minimize the physical, social and behavioral impacts of overseas travel. Tour groups will often work with local and indigenous communities to design respectful and memorable programs for visitors.",
		   "Tesla actually worked for Edison early in his career. Edison offered to pay him the modern equivalent of a million dollars to fix the problems he was having with his DC generators and motors. Tesla fixed Edison’s machines and when he asked for the money he was promised, Edison laughed him off and had this to say, Tesla, you don’t understand our American humor.",
		   "Tesla came over from Graz and went to work for Thomas Edison. Nonetheless Edison offered him a job, promising Tesla fifty thousand dollars if Tesla could redesign Edison’s breakdown-prone DC generator designs. The new generator designs were a vast improvement over Edison’s originals. Upon completing the job Tesla went to Edison to collect the$50,000 promised for the task. Tesla, Edison replied, you don’t understand our American humor. And Tesla was never paid.",
		   "How do we imagine the unimaginable If we’re asked to think of an object say, a yellow tulip a picture immediately forms in our mind’s eye? But what if we try to imagine a concept such as the square root of negative number?",
		   "While blue is one of the most popular colors, it is one of the least appetizing. Blue food is rare in nature. Food researchers say that when humans searched for food, they learned to avoid toxic or spoiled objects, which were often blue, black, or purple. When food dyed blue is served to study objects, they lose appetite."
                  ]

# Remove old database
WriteFrDic.all.each do |k|
  k.destroy
end
ReadAloud.all.each do |k|
  k.destroy
end

# Create Write From Dictation database 
wfd.each do |name, content|
  
  WriteFrDic.create(audio: name, result: content)

end

# Create Read Aloud database
read_aloud_hard.each do |content|
  ReadAloud.create(content: content)
end

read_aloud_easy.each do |content|
  ReadAloud.create(content: content)
end
